"""
Database models and async engine setup.
Uses SQLAlchemy 2.0 async with SQLite (upgradeable to PostgreSQL).
"""

from __future__ import annotations

from datetime import datetime, timezone

from sqlalchemy import String, Text, Float, Integer, Boolean, DateTime, JSON
from sqlalchemy.ext.asyncio import AsyncSession, async_sessionmaker, create_async_engine
from sqlalchemy.orm import DeclarativeBase, Mapped, mapped_column

from src.utils.config import get_settings, DATA_DIR


# ── Base ──────────────────────────────────────────────

class Base(DeclarativeBase):
    pass


# ── Models ────────────────────────────────────────────

class Article(Base):
    """A piece of content collected from any source."""

    __tablename__ = "articles"

    id: Mapped[int] = mapped_column(primary_key=True, autoincrement=True)
    source_name: Mapped[str] = mapped_column(String(200))
    source_url: Mapped[str] = mapped_column(String(500))
    title: Mapped[str] = mapped_column(String(500))
    summary: Mapped[str] = mapped_column(Text, default="")
    content: Mapped[str] = mapped_column(Text, default="")
    url: Mapped[str] = mapped_column(String(500), default="")
    category: Mapped[str] = mapped_column(String(50), default="tech")
    published_at: Mapped[datetime | None] = mapped_column(DateTime, nullable=True)
    collected_at: Mapped[datetime] = mapped_column(
        DateTime, default=lambda: datetime.now(timezone.utc)
    )
    relevance_score: Mapped[float] = mapped_column(Float, default=0.0)
    weight: Mapped[float] = mapped_column(Float, default=1.0)
    used: Mapped[bool] = mapped_column(Boolean, default=False)


class GeneratedPost(Base):
    """A LinkedIn post generated by the agent."""

    __tablename__ = "generated_posts"

    id: Mapped[int] = mapped_column(primary_key=True, autoincrement=True)
    pipeline_date: Mapped[str] = mapped_column(String(10))  # YYYY-MM-DD
    topic: Mapped[str] = mapped_column(String(255), default="")
    angle: Mapped[str] = mapped_column(String(50), default="")
    post_text: Mapped[str] = mapped_column(Text)
    source_title: Mapped[str] = mapped_column(String(500), default="")
    source_url: Mapped[str] = mapped_column(String(500), default="")
    hashtags: Mapped[str] = mapped_column(String(300), default="")
    virality_score: Mapped[float] = mapped_column(Float, default=0.0)
    score_breakdown: Mapped[dict | None] = mapped_column(JSON, nullable=True)
    voice_match_score: Mapped[float] = mapped_column(Float, default=0.0)
    was_selected: Mapped[bool] = mapped_column(Boolean, default=False)
    created_at: Mapped[datetime] = mapped_column(
        DateTime, default=lambda: datetime.now(timezone.utc)
    )


class MemoryNode(Base):
    """Content memory — tracks every topic the agent has covered."""

    __tablename__ = "memory_nodes"

    id: Mapped[int] = mapped_column(primary_key=True, autoincrement=True)
    topic: Mapped[str] = mapped_column(String(255), unique=True)
    category: Mapped[str] = mapped_column(String(100), default="")
    times_covered: Mapped[int] = mapped_column(Integer, default=0)
    last_covered: Mapped[datetime | None] = mapped_column(DateTime, nullable=True)
    angles_used: Mapped[list] = mapped_column(JSON, default=list)
    avg_performance: Mapped[float | None] = mapped_column(Float, nullable=True)
    created_at: Mapped[datetime] = mapped_column(
        DateTime, default=lambda: datetime.now(timezone.utc)
    )


# ── Engine & Session ──────────────────────────────────

_engine = None
_session_factory = None


async def get_engine():
    global _engine
    if _engine is None:
        DATA_DIR.mkdir(parents=True, exist_ok=True)
        url = get_settings().database_url
        _engine = create_async_engine(url, echo=False)
        async with _engine.begin() as conn:
            await conn.run_sync(Base.metadata.create_all)
    return _engine


async def get_session() -> AsyncSession:
    global _session_factory
    engine = await get_engine()
    if _session_factory is None:
        _session_factory = async_sessionmaker(engine, expire_on_commit=False)
    return _session_factory()
